// <auto-generated />
using System;
using FoodOrderDAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FoodOrderDAL.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20240501134015_InitFoodOrders")]
    partial class InitFoodOrders
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FoodOrderDomain.AddressInformations", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("AddressDetail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CityID")
                        .HasColumnType("int");

                    b.Property<int?>("CountryID")
                        .HasColumnType("int");

                    b.Property<int?>("CountyID")
                        .HasColumnType("int");

                    b.Property<int>("CustomerID")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.HasIndex("CityID");

                    b.HasIndex("CountryID");

                    b.HasIndex("CountyID");

                    b.HasIndex("CustomerID");

                    b.ToTable("AddressInformations");
                });

            modelBuilder.Entity("FoodOrderDomain.Categories", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            AddedDate = new DateTime(2024, 5, 1, 16, 40, 15, 557, DateTimeKind.Local).AddTicks(9341),
                            CategoryName = "Yiyecek",
                            ModifiedDate = new DateTime(2024, 5, 1, 16, 40, 15, 557, DateTimeKind.Local).AddTicks(9342),
                            Status = true
                        },
                        new
                        {
                            ID = 2,
                            AddedDate = new DateTime(2024, 5, 1, 16, 40, 15, 557, DateTimeKind.Local).AddTicks(9343),
                            CategoryName = "İçecek",
                            ModifiedDate = new DateTime(2024, 5, 1, 16, 40, 15, 557, DateTimeKind.Local).AddTicks(9344),
                            Status = true
                        });
                });

            modelBuilder.Entity("FoodOrderDomain.Cities", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CountryID")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.HasIndex("CountryID");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            AddedDate = new DateTime(2024, 5, 1, 16, 40, 15, 557, DateTimeKind.Local).AddTicks(8877),
                            CityName = "İstanbul",
                            CountryID = 1,
                            ModifiedDate = new DateTime(2024, 5, 1, 16, 40, 15, 557, DateTimeKind.Local).AddTicks(8877),
                            Status = true
                        },
                        new
                        {
                            ID = 2,
                            AddedDate = new DateTime(2024, 5, 1, 16, 40, 15, 557, DateTimeKind.Local).AddTicks(8880),
                            CityName = "Ankara",
                            CountryID = 1,
                            ModifiedDate = new DateTime(2024, 5, 1, 16, 40, 15, 557, DateTimeKind.Local).AddTicks(8880),
                            Status = true
                        },
                        new
                        {
                            ID = 3,
                            AddedDate = new DateTime(2024, 5, 1, 16, 40, 15, 557, DateTimeKind.Local).AddTicks(8882),
                            CityName = "İzmir",
                            CountryID = 1,
                            ModifiedDate = new DateTime(2024, 5, 1, 16, 40, 15, 557, DateTimeKind.Local).AddTicks(8882),
                            Status = true
                        },
                        new
                        {
                            ID = 4,
                            AddedDate = new DateTime(2024, 5, 1, 16, 40, 15, 557, DateTimeKind.Local).AddTicks(8884),
                            CityName = "Bursa",
                            CountryID = 1,
                            ModifiedDate = new DateTime(2024, 5, 1, 16, 40, 15, 557, DateTimeKind.Local).AddTicks(8884),
                            Status = true
                        },
                        new
                        {
                            ID = 5,
                            AddedDate = new DateTime(2024, 5, 1, 16, 40, 15, 557, DateTimeKind.Local).AddTicks(8886),
                            CityName = "Antalya",
                            CountryID = 1,
                            ModifiedDate = new DateTime(2024, 5, 1, 16, 40, 15, 557, DateTimeKind.Local).AddTicks(8887),
                            Status = true
                        },
                        new
                        {
                            ID = 6,
                            AddedDate = new DateTime(2024, 5, 1, 16, 40, 15, 557, DateTimeKind.Local).AddTicks(8888),
                            CityName = "Adana",
                            CountryID = 1,
                            ModifiedDate = new DateTime(2024, 5, 1, 16, 40, 15, 557, DateTimeKind.Local).AddTicks(8889),
                            Status = true
                        },
                        new
                        {
                            ID = 7,
                            AddedDate = new DateTime(2024, 5, 1, 16, 40, 15, 557, DateTimeKind.Local).AddTicks(8891),
                            CityName = "Konya",
                            CountryID = 1,
                            ModifiedDate = new DateTime(2024, 5, 1, 16, 40, 15, 557, DateTimeKind.Local).AddTicks(8891),
                            Status = true
                        },
                        new
                        {
                            ID = 8,
                            AddedDate = new DateTime(2024, 5, 1, 16, 40, 15, 557, DateTimeKind.Local).AddTicks(8893),
                            CityName = "Kayseri",
                            CountryID = 1,
                            ModifiedDate = new DateTime(2024, 5, 1, 16, 40, 15, 557, DateTimeKind.Local).AddTicks(8893),
                            Status = true
                        },
                        new
                        {
                            ID = 9,
                            AddedDate = new DateTime(2024, 5, 1, 16, 40, 15, 557, DateTimeKind.Local).AddTicks(8895),
                            CityName = "Mersin",
                            CountryID = 1,
                            ModifiedDate = new DateTime(2024, 5, 1, 16, 40, 15, 557, DateTimeKind.Local).AddTicks(8895),
                            Status = true
                        });
                });

            modelBuilder.Entity("FoodOrderDomain.ContactInformations", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ContactTypeID")
                        .HasColumnType("int");

                    b.Property<int>("CountryCode")
                        .HasColumnType("int");

                    b.Property<int>("CustomerID")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PhoneNumber")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.HasIndex("ContactTypeID");

                    b.HasIndex("CustomerID");

                    b.ToTable("ContactInformations");
                });

            modelBuilder.Entity("FoodOrderDomain.ContactTypes", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ContactType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.ToTable("ContactTypes");
                });

            modelBuilder.Entity("FoodOrderDomain.Counties", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CityID")
                        .HasColumnType("int");

                    b.Property<string>("CountyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.HasIndex("CityID");

                    b.ToTable("Counties");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            AddedDate = new DateTime(2024, 5, 1, 16, 40, 15, 557, DateTimeKind.Local).AddTicks(8989),
                            CityID = 1,
                            CountyName = "Kağıthane",
                            ModifiedDate = new DateTime(2024, 5, 1, 16, 40, 15, 557, DateTimeKind.Local).AddTicks(8990),
                            Status = true
                        },
                        new
                        {
                            ID = 2,
                            AddedDate = new DateTime(2024, 5, 1, 16, 40, 15, 557, DateTimeKind.Local).AddTicks(8992),
                            CityID = 1,
                            CountyName = "Şişli",
                            ModifiedDate = new DateTime(2024, 5, 1, 16, 40, 15, 557, DateTimeKind.Local).AddTicks(8992),
                            Status = true
                        },
                        new
                        {
                            ID = 3,
                            AddedDate = new DateTime(2024, 5, 1, 16, 40, 15, 557, DateTimeKind.Local).AddTicks(8994),
                            CityID = 1,
                            CountyName = "Beşiktaş",
                            ModifiedDate = new DateTime(2024, 5, 1, 16, 40, 15, 557, DateTimeKind.Local).AddTicks(8995),
                            Status = true
                        },
                        new
                        {
                            ID = 4,
                            AddedDate = new DateTime(2024, 5, 1, 16, 40, 15, 557, DateTimeKind.Local).AddTicks(8997),
                            CityID = 1,
                            CountyName = "Beyoğlu",
                            ModifiedDate = new DateTime(2024, 5, 1, 16, 40, 15, 557, DateTimeKind.Local).AddTicks(8997),
                            Status = true
                        },
                        new
                        {
                            ID = 5,
                            AddedDate = new DateTime(2024, 5, 1, 16, 40, 15, 557, DateTimeKind.Local).AddTicks(8999),
                            CityID = 1,
                            CountyName = "Kadıköy",
                            ModifiedDate = new DateTime(2024, 5, 1, 16, 40, 15, 557, DateTimeKind.Local).AddTicks(8999),
                            Status = true
                        },
                        new
                        {
                            ID = 6,
                            AddedDate = new DateTime(2024, 5, 1, 16, 40, 15, 557, DateTimeKind.Local).AddTicks(9001),
                            CityID = 1,
                            CountyName = "Üsküdar",
                            ModifiedDate = new DateTime(2024, 5, 1, 16, 40, 15, 557, DateTimeKind.Local).AddTicks(9001),
                            Status = true
                        },
                        new
                        {
                            ID = 7,
                            AddedDate = new DateTime(2024, 5, 1, 16, 40, 15, 557, DateTimeKind.Local).AddTicks(9003),
                            CityID = 1,
                            CountyName = "Fatih",
                            ModifiedDate = new DateTime(2024, 5, 1, 16, 40, 15, 557, DateTimeKind.Local).AddTicks(9003),
                            Status = true
                        },
                        new
                        {
                            ID = 8,
                            AddedDate = new DateTime(2024, 5, 1, 16, 40, 15, 557, DateTimeKind.Local).AddTicks(9005),
                            CityID = 1,
                            CountyName = "Bakırköy",
                            ModifiedDate = new DateTime(2024, 5, 1, 16, 40, 15, 557, DateTimeKind.Local).AddTicks(9006),
                            Status = true
                        },
                        new
                        {
                            ID = 9,
                            AddedDate = new DateTime(2024, 5, 1, 16, 40, 15, 557, DateTimeKind.Local).AddTicks(9007),
                            CityID = 1,
                            CountyName = "Maltepe",
                            ModifiedDate = new DateTime(2024, 5, 1, 16, 40, 15, 557, DateTimeKind.Local).AddTicks(9008),
                            Status = true
                        },
                        new
                        {
                            ID = 10,
                            AddedDate = new DateTime(2024, 5, 1, 16, 40, 15, 557, DateTimeKind.Local).AddTicks(9009),
                            CityID = 1,
                            CountyName = "Ataşehir",
                            ModifiedDate = new DateTime(2024, 5, 1, 16, 40, 15, 557, DateTimeKind.Local).AddTicks(9010),
                            Status = true
                        },
                        new
                        {
                            ID = 11,
                            AddedDate = new DateTime(2024, 5, 1, 16, 40, 15, 557, DateTimeKind.Local).AddTicks(9011),
                            CityID = 1,
                            CountyName = "Büyükçekmece",
                            ModifiedDate = new DateTime(2024, 5, 1, 16, 40, 15, 557, DateTimeKind.Local).AddTicks(9012),
                            Status = true
                        },
                        new
                        {
                            ID = 12,
                            AddedDate = new DateTime(2024, 5, 1, 16, 40, 15, 557, DateTimeKind.Local).AddTicks(9014),
                            CityID = 1,
                            CountyName = "Sarıyer",
                            ModifiedDate = new DateTime(2024, 5, 1, 16, 40, 15, 557, DateTimeKind.Local).AddTicks(9014),
                            Status = true
                        },
                        new
                        {
                            ID = 13,
                            AddedDate = new DateTime(2024, 5, 1, 16, 40, 15, 557, DateTimeKind.Local).AddTicks(9016),
                            CityID = 1,
                            CountyName = "Kartal",
                            ModifiedDate = new DateTime(2024, 5, 1, 16, 40, 15, 557, DateTimeKind.Local).AddTicks(9016),
                            Status = true
                        },
                        new
                        {
                            ID = 14,
                            AddedDate = new DateTime(2024, 5, 1, 16, 40, 15, 557, DateTimeKind.Local).AddTicks(9018),
                            CityID = 1,
                            CountyName = "Şile",
                            ModifiedDate = new DateTime(2024, 5, 1, 16, 40, 15, 557, DateTimeKind.Local).AddTicks(9018),
                            Status = true
                        },
                        new
                        {
                            ID = 15,
                            AddedDate = new DateTime(2024, 5, 1, 16, 40, 15, 557, DateTimeKind.Local).AddTicks(9020),
                            CityID = 1,
                            CountyName = "Çatalca",
                            ModifiedDate = new DateTime(2024, 5, 1, 16, 40, 15, 557, DateTimeKind.Local).AddTicks(9020),
                            Status = true
                        },
                        new
                        {
                            ID = 16,
                            AddedDate = new DateTime(2024, 5, 1, 16, 40, 15, 557, DateTimeKind.Local).AddTicks(9022),
                            CityID = 1,
                            CountyName = "Adalar",
                            ModifiedDate = new DateTime(2024, 5, 1, 16, 40, 15, 557, DateTimeKind.Local).AddTicks(9023),
                            Status = true
                        },
                        new
                        {
                            ID = 17,
                            AddedDate = new DateTime(2024, 5, 1, 16, 40, 15, 557, DateTimeKind.Local).AddTicks(9024),
                            CityID = 2,
                            CountyName = "Altındağ",
                            ModifiedDate = new DateTime(2024, 5, 1, 16, 40, 15, 557, DateTimeKind.Local).AddTicks(9025),
                            Status = true
                        },
                        new
                        {
                            ID = 18,
                            AddedDate = new DateTime(2024, 5, 1, 16, 40, 15, 557, DateTimeKind.Local).AddTicks(9026),
                            CityID = 2,
                            CountyName = "Ayaş",
                            ModifiedDate = new DateTime(2024, 5, 1, 16, 40, 15, 557, DateTimeKind.Local).AddTicks(9027),
                            Status = true
                        },
                        new
                        {
                            ID = 19,
                            AddedDate = new DateTime(2024, 5, 1, 16, 40, 15, 557, DateTimeKind.Local).AddTicks(9029),
                            CityID = 2,
                            CountyName = "Bala",
                            ModifiedDate = new DateTime(2024, 5, 1, 16, 40, 15, 557, DateTimeKind.Local).AddTicks(9029),
                            Status = true
                        });
                });

            modelBuilder.Entity("FoodOrderDomain.Countries", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            AddedDate = new DateTime(2024, 5, 1, 16, 40, 15, 557, DateTimeKind.Local).AddTicks(9134),
                            CountryName = "Türkiye",
                            ModifiedDate = new DateTime(2024, 5, 1, 16, 40, 15, 557, DateTimeKind.Local).AddTicks(9135),
                            Status = true
                        },
                        new
                        {
                            ID = 2,
                            AddedDate = new DateTime(2024, 5, 1, 16, 40, 15, 557, DateTimeKind.Local).AddTicks(9137),
                            CountryName = "Almanya",
                            ModifiedDate = new DateTime(2024, 5, 1, 16, 40, 15, 557, DateTimeKind.Local).AddTicks(9137),
                            Status = true
                        },
                        new
                        {
                            ID = 3,
                            AddedDate = new DateTime(2024, 5, 1, 16, 40, 15, 557, DateTimeKind.Local).AddTicks(9139),
                            CountryName = "Fransa",
                            ModifiedDate = new DateTime(2024, 5, 1, 16, 40, 15, 557, DateTimeKind.Local).AddTicks(9140),
                            Status = true
                        },
                        new
                        {
                            ID = 4,
                            AddedDate = new DateTime(2024, 5, 1, 16, 40, 15, 557, DateTimeKind.Local).AddTicks(9142),
                            CountryName = "İngiltere",
                            ModifiedDate = new DateTime(2024, 5, 1, 16, 40, 15, 557, DateTimeKind.Local).AddTicks(9142),
                            Status = true
                        },
                        new
                        {
                            ID = 5,
                            AddedDate = new DateTime(2024, 5, 1, 16, 40, 15, 557, DateTimeKind.Local).AddTicks(9144),
                            CountryName = "İtalya",
                            ModifiedDate = new DateTime(2024, 5, 1, 16, 40, 15, 557, DateTimeKind.Local).AddTicks(9145),
                            Status = true
                        },
                        new
                        {
                            ID = 6,
                            AddedDate = new DateTime(2024, 5, 1, 16, 40, 15, 557, DateTimeKind.Local).AddTicks(9146),
                            CountryName = "İspanya",
                            ModifiedDate = new DateTime(2024, 5, 1, 16, 40, 15, 557, DateTimeKind.Local).AddTicks(9147),
                            Status = true
                        },
                        new
                        {
                            ID = 7,
                            AddedDate = new DateTime(2024, 5, 1, 16, 40, 15, 557, DateTimeKind.Local).AddTicks(9148),
                            CountryName = "Türkiye",
                            ModifiedDate = new DateTime(2024, 5, 1, 16, 40, 15, 557, DateTimeKind.Local).AddTicks(9149),
                            Status = true
                        },
                        new
                        {
                            ID = 8,
                            AddedDate = new DateTime(2024, 5, 1, 16, 40, 15, 557, DateTimeKind.Local).AddTicks(9151),
                            CountryName = "Ukrayna",
                            ModifiedDate = new DateTime(2024, 5, 1, 16, 40, 15, 557, DateTimeKind.Local).AddTicks(9151),
                            Status = true
                        },
                        new
                        {
                            ID = 9,
                            AddedDate = new DateTime(2024, 5, 1, 16, 40, 15, 557, DateTimeKind.Local).AddTicks(9153),
                            CountryName = "Polonya",
                            ModifiedDate = new DateTime(2024, 5, 1, 16, 40, 15, 557, DateTimeKind.Local).AddTicks(9153),
                            Status = true
                        },
                        new
                        {
                            ID = 10,
                            AddedDate = new DateTime(2024, 5, 1, 16, 40, 15, 557, DateTimeKind.Local).AddTicks(9155),
                            CountryName = "Romanya",
                            ModifiedDate = new DateTime(2024, 5, 1, 16, 40, 15, 557, DateTimeKind.Local).AddTicks(9155),
                            Status = true
                        },
                        new
                        {
                            ID = 11,
                            AddedDate = new DateTime(2024, 5, 1, 16, 40, 15, 557, DateTimeKind.Local).AddTicks(9157),
                            CountryName = "Hollanda",
                            ModifiedDate = new DateTime(2024, 5, 1, 16, 40, 15, 557, DateTimeKind.Local).AddTicks(9158),
                            Status = true
                        });
                });

            modelBuilder.Entity("FoodOrderDomain.Customers", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GenderID")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ID");

                    b.HasIndex("GenderID");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("FoodOrderDomain.Genders", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.ToTable("Genders");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            AddedDate = new DateTime(2024, 5, 1, 16, 40, 15, 557, DateTimeKind.Local).AddTicks(9246),
                            Gender = "Kadın",
                            ModifiedDate = new DateTime(2024, 5, 1, 16, 40, 15, 557, DateTimeKind.Local).AddTicks(9246),
                            Status = true
                        },
                        new
                        {
                            ID = 2,
                            AddedDate = new DateTime(2024, 5, 1, 16, 40, 15, 557, DateTimeKind.Local).AddTicks(9248),
                            Gender = "Erkek",
                            ModifiedDate = new DateTime(2024, 5, 1, 16, 40, 15, 557, DateTimeKind.Local).AddTicks(9249),
                            Status = true
                        });
                });

            modelBuilder.Entity("FoodOrderDomain.Menu", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsAllergen")
                        .HasColumnType("bit");

                    b.Property<string>("MenuName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PreparationTime")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.ToTable("Menu");
                });

            modelBuilder.Entity("FoodOrderDomain.OrderDetails", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ItemID")
                        .HasColumnType("int");

                    b.Property<int>("ItemType")
                        .HasColumnType("int");

                    b.Property<int>("MenuID")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.HasIndex("MenuID");

                    b.HasIndex("ProductID");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("FoodOrderDomain.OrderStates", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrderState")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.ToTable("OrderStates");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            AddedDate = new DateTime(2024, 5, 1, 16, 40, 15, 557, DateTimeKind.Local).AddTicks(8553),
                            ModifiedDate = new DateTime(2024, 5, 1, 16, 40, 15, 557, DateTimeKind.Local).AddTicks(8553),
                            OrderState = "Hazırlanıyor",
                            Status = true
                        },
                        new
                        {
                            ID = 2,
                            AddedDate = new DateTime(2024, 5, 1, 16, 40, 15, 557, DateTimeKind.Local).AddTicks(8555),
                            ModifiedDate = new DateTime(2024, 5, 1, 16, 40, 15, 557, DateTimeKind.Local).AddTicks(8556),
                            OrderState = "Teslim Edildi",
                            Status = true
                        },
                        new
                        {
                            ID = 3,
                            AddedDate = new DateTime(2024, 5, 1, 16, 40, 15, 557, DateTimeKind.Local).AddTicks(8558),
                            ModifiedDate = new DateTime(2024, 5, 1, 16, 40, 15, 557, DateTimeKind.Local).AddTicks(8558),
                            OrderState = "İptal Edildi",
                            Status = true
                        });
                });

            modelBuilder.Entity("FoodOrderDomain.Orders", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("AddressID")
                        .HasColumnType("int");

                    b.Property<int?>("ContactID")
                        .HasColumnType("int");

                    b.Property<int?>("CustomerID")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("OrderDetailsID")
                        .HasColumnType("int");

                    b.Property<string>("OrderNotes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderStateID")
                        .HasColumnType("int");

                    b.Property<int>("PaymentMethodID")
                        .HasColumnType("int");

                    b.Property<bool>("PaymentStatus")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.HasIndex("AddressID");

                    b.HasIndex("ContactID");

                    b.HasIndex("CustomerID");

                    b.HasIndex("OrderDetailsID");

                    b.HasIndex("OrderStateID");

                    b.HasIndex("PaymentMethodID");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("FoodOrderDomain.PaymentMethods", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.ToTable("PaymentMethods");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            AddedDate = new DateTime(2024, 5, 1, 16, 40, 15, 557, DateTimeKind.Local).AddTicks(8788),
                            ModifiedDate = new DateTime(2024, 5, 1, 16, 40, 15, 557, DateTimeKind.Local).AddTicks(8788),
                            PaymentName = "Kredi/Banka Kartı",
                            Status = true
                        },
                        new
                        {
                            ID = 2,
                            AddedDate = new DateTime(2024, 5, 1, 16, 40, 15, 557, DateTimeKind.Local).AddTicks(8791),
                            ModifiedDate = new DateTime(2024, 5, 1, 16, 40, 15, 557, DateTimeKind.Local).AddTicks(8791),
                            PaymentName = "Nakit",
                            Status = true
                        });
                });

            modelBuilder.Entity("FoodOrderDomain.ProductDetails", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.HasIndex("ProductID")
                        .IsUnique();

                    b.ToTable("ProductDetails");
                });

            modelBuilder.Entity("FoodOrderDomain.ProductMenu", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("MenuID")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.HasIndex("MenuID");

                    b.HasIndex("ProductID");

                    b.ToTable("ProductMenu");
                });

            modelBuilder.Entity("FoodOrderDomain.Products", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PreparationTime")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductDetailID")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.HasIndex("CategoryID");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            AddedDate = new DateTime(2024, 5, 1, 16, 40, 15, 557, DateTimeKind.Local).AddTicks(9435),
                            CategoryID = 1,
                            ModifiedDate = new DateTime(2024, 5, 1, 16, 40, 15, 557, DateTimeKind.Local).AddTicks(9435),
                            PreparationTime = 5,
                            Price = 15m,
                            ProductDetailID = 0,
                            ProductName = "Patates",
                            Status = true
                        },
                        new
                        {
                            ID = 2,
                            AddedDate = new DateTime(2024, 5, 1, 16, 40, 15, 557, DateTimeKind.Local).AddTicks(9438),
                            CategoryID = 2,
                            ModifiedDate = new DateTime(2024, 5, 1, 16, 40, 15, 557, DateTimeKind.Local).AddTicks(9438),
                            PreparationTime = 0,
                            Price = 10m,
                            ProductDetailID = 0,
                            ProductName = "Kola",
                            Status = true
                        });
                });

            modelBuilder.Entity("FoodOrderDomain.Stock", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("MenuID")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<int>("StockAmount")
                        .HasColumnType("int");

                    b.Property<bool>("StockStatus")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.HasIndex("MenuID")
                        .IsUnique();

                    b.HasIndex("ProductID")
                        .IsUnique();

                    b.ToTable("Stocks");
                });

            modelBuilder.Entity("FoodOrderDomain.AddressInformations", b =>
                {
                    b.HasOne("FoodOrderDomain.Cities", "City")
                        .WithMany("AddressInfo")
                        .HasForeignKey("CityID");

                    b.HasOne("FoodOrderDomain.Countries", "Country")
                        .WithMany("AddressInfo")
                        .HasForeignKey("CountryID");

                    b.HasOne("FoodOrderDomain.Counties", "County")
                        .WithMany("AddressInfo")
                        .HasForeignKey("CountyID");

                    b.HasOne("FoodOrderDomain.Customers", "Customer")
                        .WithMany("AddressInfo")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("Country");

                    b.Navigation("County");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("FoodOrderDomain.Cities", b =>
                {
                    b.HasOne("FoodOrderDomain.Countries", "Country")
                        .WithMany("City")
                        .HasForeignKey("CountryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("FoodOrderDomain.ContactInformations", b =>
                {
                    b.HasOne("FoodOrderDomain.ContactTypes", "ContactType")
                        .WithMany("ContactInfo")
                        .HasForeignKey("ContactTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FoodOrderDomain.Customers", "Customer")
                        .WithMany("ContactInfo")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContactType");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("FoodOrderDomain.Counties", b =>
                {
                    b.HasOne("FoodOrderDomain.Cities", "City")
                        .WithMany("County")
                        .HasForeignKey("CityID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("FoodOrderDomain.Customers", b =>
                {
                    b.HasOne("FoodOrderDomain.Genders", "Gender")
                        .WithMany("Customers")
                        .HasForeignKey("GenderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gender");
                });

            modelBuilder.Entity("FoodOrderDomain.OrderDetails", b =>
                {
                    b.HasOne("FoodOrderDomain.Menu", "Menu")
                        .WithMany()
                        .HasForeignKey("MenuID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FoodOrderDomain.Products", "Product")
                        .WithMany()
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Menu");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("FoodOrderDomain.Orders", b =>
                {
                    b.HasOne("FoodOrderDomain.AddressInformations", "Address")
                        .WithMany("Orders")
                        .HasForeignKey("AddressID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FoodOrderDomain.ContactInformations", "ContactInfo")
                        .WithMany("Orders")
                        .HasForeignKey("ContactID");

                    b.HasOne("FoodOrderDomain.Customers", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerID");

                    b.HasOne("FoodOrderDomain.OrderDetails", null)
                        .WithMany("Orders")
                        .HasForeignKey("OrderDetailsID");

                    b.HasOne("FoodOrderDomain.OrderStates", "OrderState")
                        .WithMany("Orders")
                        .HasForeignKey("OrderStateID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FoodOrderDomain.PaymentMethods", "PaymentMethod")
                        .WithMany("Orders")
                        .HasForeignKey("PaymentMethodID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("ContactInfo");

                    b.Navigation("Customer");

                    b.Navigation("OrderState");

                    b.Navigation("PaymentMethod");
                });

            modelBuilder.Entity("FoodOrderDomain.ProductDetails", b =>
                {
                    b.HasOne("FoodOrderDomain.Products", "Product")
                        .WithOne("ProductDetail")
                        .HasForeignKey("FoodOrderDomain.ProductDetails", "ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("FoodOrderDomain.ProductMenu", b =>
                {
                    b.HasOne("FoodOrderDomain.Menu", "Menu")
                        .WithMany()
                        .HasForeignKey("MenuID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FoodOrderDomain.Products", "Product")
                        .WithMany()
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Menu");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("FoodOrderDomain.Products", b =>
                {
                    b.HasOne("FoodOrderDomain.Categories", "Category")
                        .WithMany("Product")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("FoodOrderDomain.Stock", b =>
                {
                    b.HasOne("FoodOrderDomain.Menu", "Menu")
                        .WithOne("Stock")
                        .HasForeignKey("FoodOrderDomain.Stock", "MenuID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FoodOrderDomain.Products", "Product")
                        .WithOne("Stock")
                        .HasForeignKey("FoodOrderDomain.Stock", "ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Menu");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("FoodOrderDomain.AddressInformations", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("FoodOrderDomain.Categories", b =>
                {
                    b.Navigation("Product");
                });

            modelBuilder.Entity("FoodOrderDomain.Cities", b =>
                {
                    b.Navigation("AddressInfo");

                    b.Navigation("County");
                });

            modelBuilder.Entity("FoodOrderDomain.ContactInformations", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("FoodOrderDomain.ContactTypes", b =>
                {
                    b.Navigation("ContactInfo");
                });

            modelBuilder.Entity("FoodOrderDomain.Counties", b =>
                {
                    b.Navigation("AddressInfo");
                });

            modelBuilder.Entity("FoodOrderDomain.Countries", b =>
                {
                    b.Navigation("AddressInfo");

                    b.Navigation("City");
                });

            modelBuilder.Entity("FoodOrderDomain.Customers", b =>
                {
                    b.Navigation("AddressInfo");

                    b.Navigation("ContactInfo");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("FoodOrderDomain.Genders", b =>
                {
                    b.Navigation("Customers");
                });

            modelBuilder.Entity("FoodOrderDomain.Menu", b =>
                {
                    b.Navigation("Stock")
                        .IsRequired();
                });

            modelBuilder.Entity("FoodOrderDomain.OrderDetails", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("FoodOrderDomain.OrderStates", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("FoodOrderDomain.PaymentMethods", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("FoodOrderDomain.Products", b =>
                {
                    b.Navigation("ProductDetail")
                        .IsRequired();

                    b.Navigation("Stock")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
