// <auto-generated />
using System;
using FoodOrderDAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FoodOrderDAL.Migrations
{
    [DbContext(typeof(AppDBContext))]
    partial class AppDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FoodOrderDomain.AddressInformations", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("AddressDetail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CityID")
                        .HasColumnType("int");

                    b.Property<int?>("CountryID")
                        .HasColumnType("int");

                    b.Property<int?>("CountyID")
                        .HasColumnType("int");

                    b.Property<int>("CustomerID")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.HasIndex("CityID");

                    b.HasIndex("CountryID");

                    b.HasIndex("CountyID");

                    b.HasIndex("CustomerID");

                    b.ToTable("AddressInformations");
                });

            modelBuilder.Entity("FoodOrderDomain.Categories", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("FoodOrderDomain.Cities", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CountryID")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.HasIndex("CountryID");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            AddedDate = new DateTime(2024, 4, 27, 19, 39, 46, 501, DateTimeKind.Local).AddTicks(4591),
                            CityName = "İstanbul",
                            CountryID = 1,
                            ModifiedDate = new DateTime(2024, 4, 27, 19, 39, 46, 501, DateTimeKind.Local).AddTicks(4591),
                            Status = true
                        },
                        new
                        {
                            ID = 2,
                            AddedDate = new DateTime(2024, 4, 27, 19, 39, 46, 501, DateTimeKind.Local).AddTicks(4593),
                            CityName = "Ankara",
                            CountryID = 6,
                            ModifiedDate = new DateTime(2024, 4, 27, 19, 39, 46, 501, DateTimeKind.Local).AddTicks(4593),
                            Status = true
                        },
                        new
                        {
                            ID = 3,
                            AddedDate = new DateTime(2024, 4, 27, 19, 39, 46, 501, DateTimeKind.Local).AddTicks(4595),
                            CityName = "İzmir",
                            CountryID = 6,
                            ModifiedDate = new DateTime(2024, 4, 27, 19, 39, 46, 501, DateTimeKind.Local).AddTicks(4595),
                            Status = true
                        },
                        new
                        {
                            ID = 4,
                            AddedDate = new DateTime(2024, 4, 27, 19, 39, 46, 501, DateTimeKind.Local).AddTicks(4597),
                            CityName = "Bursa",
                            CountryID = 6,
                            ModifiedDate = new DateTime(2024, 4, 27, 19, 39, 46, 501, DateTimeKind.Local).AddTicks(4597),
                            Status = true
                        },
                        new
                        {
                            ID = 5,
                            AddedDate = new DateTime(2024, 4, 27, 19, 39, 46, 501, DateTimeKind.Local).AddTicks(4599),
                            CityName = "Antalya",
                            CountryID = 6,
                            ModifiedDate = new DateTime(2024, 4, 27, 19, 39, 46, 501, DateTimeKind.Local).AddTicks(4599),
                            Status = true
                        },
                        new
                        {
                            ID = 6,
                            AddedDate = new DateTime(2024, 4, 27, 19, 39, 46, 501, DateTimeKind.Local).AddTicks(4601),
                            CityName = "Adana",
                            CountryID = 6,
                            ModifiedDate = new DateTime(2024, 4, 27, 19, 39, 46, 501, DateTimeKind.Local).AddTicks(4602),
                            Status = true
                        },
                        new
                        {
                            ID = 7,
                            AddedDate = new DateTime(2024, 4, 27, 19, 39, 46, 501, DateTimeKind.Local).AddTicks(4603),
                            CityName = "Konya",
                            CountryID = 6,
                            ModifiedDate = new DateTime(2024, 4, 27, 19, 39, 46, 501, DateTimeKind.Local).AddTicks(4604),
                            Status = true
                        },
                        new
                        {
                            ID = 8,
                            AddedDate = new DateTime(2024, 4, 27, 19, 39, 46, 501, DateTimeKind.Local).AddTicks(4605),
                            CityName = "Kayseri",
                            CountryID = 6,
                            ModifiedDate = new DateTime(2024, 4, 27, 19, 39, 46, 501, DateTimeKind.Local).AddTicks(4606),
                            Status = true
                        },
                        new
                        {
                            ID = 9,
                            AddedDate = new DateTime(2024, 4, 27, 19, 39, 46, 501, DateTimeKind.Local).AddTicks(4607),
                            CityName = "Mersin",
                            CountryID = 6,
                            ModifiedDate = new DateTime(2024, 4, 27, 19, 39, 46, 501, DateTimeKind.Local).AddTicks(4608),
                            Status = true
                        });
                });

            modelBuilder.Entity("FoodOrderDomain.ContactInformations", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ContactTypeID")
                        .HasColumnType("int");

                    b.Property<int>("CountryCode")
                        .HasColumnType("int");

                    b.Property<int>("CustomerID")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PhoneNumber")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.HasIndex("ContactTypeID");

                    b.HasIndex("CustomerID");

                    b.ToTable("ContactInformations");
                });

            modelBuilder.Entity("FoodOrderDomain.ContactTypes", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ContactType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.ToTable("ContactTypes");
                });

            modelBuilder.Entity("FoodOrderDomain.Counties", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CityID")
                        .HasColumnType("int");

                    b.Property<string>("CountyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.HasIndex("CityID");

                    b.ToTable("Counties");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            AddedDate = new DateTime(2024, 4, 27, 19, 39, 46, 501, DateTimeKind.Local).AddTicks(4733),
                            CityID = 1,
                            CountyName = "Kağıthane",
                            ModifiedDate = new DateTime(2024, 4, 27, 19, 39, 46, 501, DateTimeKind.Local).AddTicks(4734),
                            Status = true
                        },
                        new
                        {
                            ID = 2,
                            AddedDate = new DateTime(2024, 4, 27, 19, 39, 46, 501, DateTimeKind.Local).AddTicks(4735),
                            CityID = 1,
                            CountyName = "Şişli",
                            ModifiedDate = new DateTime(2024, 4, 27, 19, 39, 46, 501, DateTimeKind.Local).AddTicks(4736),
                            Status = true
                        },
                        new
                        {
                            ID = 3,
                            AddedDate = new DateTime(2024, 4, 27, 19, 39, 46, 501, DateTimeKind.Local).AddTicks(4737),
                            CityID = 1,
                            CountyName = "Beşiktaş",
                            ModifiedDate = new DateTime(2024, 4, 27, 19, 39, 46, 501, DateTimeKind.Local).AddTicks(4738),
                            Status = true
                        },
                        new
                        {
                            ID = 4,
                            AddedDate = new DateTime(2024, 4, 27, 19, 39, 46, 501, DateTimeKind.Local).AddTicks(4740),
                            CityID = 1,
                            CountyName = "Beyoğlu",
                            ModifiedDate = new DateTime(2024, 4, 27, 19, 39, 46, 501, DateTimeKind.Local).AddTicks(4740),
                            Status = true
                        },
                        new
                        {
                            ID = 5,
                            AddedDate = new DateTime(2024, 4, 27, 19, 39, 46, 501, DateTimeKind.Local).AddTicks(4742),
                            CityID = 1,
                            CountyName = "Kadıköy",
                            ModifiedDate = new DateTime(2024, 4, 27, 19, 39, 46, 501, DateTimeKind.Local).AddTicks(4743),
                            Status = true
                        },
                        new
                        {
                            ID = 6,
                            AddedDate = new DateTime(2024, 4, 27, 19, 39, 46, 501, DateTimeKind.Local).AddTicks(4744),
                            CityID = 1,
                            CountyName = "Üsküdar",
                            ModifiedDate = new DateTime(2024, 4, 27, 19, 39, 46, 501, DateTimeKind.Local).AddTicks(4744),
                            Status = true
                        },
                        new
                        {
                            ID = 7,
                            AddedDate = new DateTime(2024, 4, 27, 19, 39, 46, 501, DateTimeKind.Local).AddTicks(4746),
                            CityID = 1,
                            CountyName = "Fatih",
                            ModifiedDate = new DateTime(2024, 4, 27, 19, 39, 46, 501, DateTimeKind.Local).AddTicks(4746),
                            Status = true
                        },
                        new
                        {
                            ID = 8,
                            AddedDate = new DateTime(2024, 4, 27, 19, 39, 46, 501, DateTimeKind.Local).AddTicks(4748),
                            CityID = 1,
                            CountyName = "Bakırköy",
                            ModifiedDate = new DateTime(2024, 4, 27, 19, 39, 46, 501, DateTimeKind.Local).AddTicks(4748),
                            Status = true
                        },
                        new
                        {
                            ID = 9,
                            AddedDate = new DateTime(2024, 4, 27, 19, 39, 46, 501, DateTimeKind.Local).AddTicks(4750),
                            CityID = 1,
                            CountyName = "Maltepe",
                            ModifiedDate = new DateTime(2024, 4, 27, 19, 39, 46, 501, DateTimeKind.Local).AddTicks(4750),
                            Status = true
                        },
                        new
                        {
                            ID = 10,
                            AddedDate = new DateTime(2024, 4, 27, 19, 39, 46, 501, DateTimeKind.Local).AddTicks(4752),
                            CityID = 1,
                            CountyName = "Ataşehir",
                            ModifiedDate = new DateTime(2024, 4, 27, 19, 39, 46, 501, DateTimeKind.Local).AddTicks(4753),
                            Status = true
                        },
                        new
                        {
                            ID = 11,
                            AddedDate = new DateTime(2024, 4, 27, 19, 39, 46, 501, DateTimeKind.Local).AddTicks(4754),
                            CityID = 1,
                            CountyName = "Büyükçekmece",
                            ModifiedDate = new DateTime(2024, 4, 27, 19, 39, 46, 501, DateTimeKind.Local).AddTicks(4755),
                            Status = true
                        },
                        new
                        {
                            ID = 12,
                            AddedDate = new DateTime(2024, 4, 27, 19, 39, 46, 501, DateTimeKind.Local).AddTicks(4756),
                            CityID = 1,
                            CountyName = "Sarıyer",
                            ModifiedDate = new DateTime(2024, 4, 27, 19, 39, 46, 501, DateTimeKind.Local).AddTicks(4757),
                            Status = true
                        },
                        new
                        {
                            ID = 13,
                            AddedDate = new DateTime(2024, 4, 27, 19, 39, 46, 501, DateTimeKind.Local).AddTicks(4758),
                            CityID = 1,
                            CountyName = "Kartal",
                            ModifiedDate = new DateTime(2024, 4, 27, 19, 39, 46, 501, DateTimeKind.Local).AddTicks(4759),
                            Status = true
                        },
                        new
                        {
                            ID = 14,
                            AddedDate = new DateTime(2024, 4, 27, 19, 39, 46, 501, DateTimeKind.Local).AddTicks(4760),
                            CityID = 1,
                            CountyName = "Şile",
                            ModifiedDate = new DateTime(2024, 4, 27, 19, 39, 46, 501, DateTimeKind.Local).AddTicks(4761),
                            Status = true
                        },
                        new
                        {
                            ID = 15,
                            AddedDate = new DateTime(2024, 4, 27, 19, 39, 46, 501, DateTimeKind.Local).AddTicks(4762),
                            CityID = 1,
                            CountyName = "Çatalca",
                            ModifiedDate = new DateTime(2024, 4, 27, 19, 39, 46, 501, DateTimeKind.Local).AddTicks(4763),
                            Status = true
                        },
                        new
                        {
                            ID = 16,
                            AddedDate = new DateTime(2024, 4, 27, 19, 39, 46, 501, DateTimeKind.Local).AddTicks(4764),
                            CityID = 1,
                            CountyName = "Adalar",
                            ModifiedDate = new DateTime(2024, 4, 27, 19, 39, 46, 501, DateTimeKind.Local).AddTicks(4765),
                            Status = true
                        });
                });

            modelBuilder.Entity("FoodOrderDomain.Countries", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            AddedDate = new DateTime(2024, 4, 27, 19, 39, 46, 501, DateTimeKind.Local).AddTicks(4897),
                            CountryName = "Türkiye",
                            ModifiedDate = new DateTime(2024, 4, 27, 19, 39, 46, 501, DateTimeKind.Local).AddTicks(4898),
                            Status = true
                        },
                        new
                        {
                            ID = 2,
                            AddedDate = new DateTime(2024, 4, 27, 19, 39, 46, 501, DateTimeKind.Local).AddTicks(4899),
                            CountryName = "Almanya",
                            ModifiedDate = new DateTime(2024, 4, 27, 19, 39, 46, 501, DateTimeKind.Local).AddTicks(4900),
                            Status = true
                        },
                        new
                        {
                            ID = 3,
                            AddedDate = new DateTime(2024, 4, 27, 19, 39, 46, 501, DateTimeKind.Local).AddTicks(4902),
                            CountryName = "Fransa",
                            ModifiedDate = new DateTime(2024, 4, 27, 19, 39, 46, 501, DateTimeKind.Local).AddTicks(4902),
                            Status = true
                        },
                        new
                        {
                            ID = 4,
                            AddedDate = new DateTime(2024, 4, 27, 19, 39, 46, 501, DateTimeKind.Local).AddTicks(4903),
                            CountryName = "İngiltere",
                            ModifiedDate = new DateTime(2024, 4, 27, 19, 39, 46, 501, DateTimeKind.Local).AddTicks(4904),
                            Status = true
                        },
                        new
                        {
                            ID = 5,
                            AddedDate = new DateTime(2024, 4, 27, 19, 39, 46, 501, DateTimeKind.Local).AddTicks(4905),
                            CountryName = "İtalya",
                            ModifiedDate = new DateTime(2024, 4, 27, 19, 39, 46, 501, DateTimeKind.Local).AddTicks(4906),
                            Status = true
                        },
                        new
                        {
                            ID = 6,
                            AddedDate = new DateTime(2024, 4, 27, 19, 39, 46, 501, DateTimeKind.Local).AddTicks(4907),
                            CountryName = "İspanya",
                            ModifiedDate = new DateTime(2024, 4, 27, 19, 39, 46, 501, DateTimeKind.Local).AddTicks(4908),
                            Status = true
                        },
                        new
                        {
                            ID = 7,
                            AddedDate = new DateTime(2024, 4, 27, 19, 39, 46, 501, DateTimeKind.Local).AddTicks(4909),
                            CountryName = "Türkiye",
                            ModifiedDate = new DateTime(2024, 4, 27, 19, 39, 46, 501, DateTimeKind.Local).AddTicks(4909),
                            Status = true
                        },
                        new
                        {
                            ID = 8,
                            AddedDate = new DateTime(2024, 4, 27, 19, 39, 46, 501, DateTimeKind.Local).AddTicks(4911),
                            CountryName = "Ukrayna",
                            ModifiedDate = new DateTime(2024, 4, 27, 19, 39, 46, 501, DateTimeKind.Local).AddTicks(4911),
                            Status = true
                        },
                        new
                        {
                            ID = 9,
                            AddedDate = new DateTime(2024, 4, 27, 19, 39, 46, 501, DateTimeKind.Local).AddTicks(4913),
                            CountryName = "Polonya",
                            ModifiedDate = new DateTime(2024, 4, 27, 19, 39, 46, 501, DateTimeKind.Local).AddTicks(4913),
                            Status = true
                        },
                        new
                        {
                            ID = 10,
                            AddedDate = new DateTime(2024, 4, 27, 19, 39, 46, 501, DateTimeKind.Local).AddTicks(4915),
                            CountryName = "Romanya",
                            ModifiedDate = new DateTime(2024, 4, 27, 19, 39, 46, 501, DateTimeKind.Local).AddTicks(4915),
                            Status = true
                        },
                        new
                        {
                            ID = 11,
                            AddedDate = new DateTime(2024, 4, 27, 19, 39, 46, 501, DateTimeKind.Local).AddTicks(4917),
                            CountryName = "Hollanda",
                            ModifiedDate = new DateTime(2024, 4, 27, 19, 39, 46, 501, DateTimeKind.Local).AddTicks(4917),
                            Status = true
                        });
                });

            modelBuilder.Entity("FoodOrderDomain.Customers", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Gender")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("FoodOrderDomain.Menu", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsAllergen")
                        .HasColumnType("bit");

                    b.Property<string>("MenuName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PreparationTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.ToTable("Menu");
                });

            modelBuilder.Entity("FoodOrderDomain.OrderDetails", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ItemID")
                        .HasColumnType("int");

                    b.Property<int>("ItemType")
                        .HasColumnType("int");

                    b.Property<int>("MenuID")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderID")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.HasIndex("MenuID");

                    b.HasIndex("OrderID");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("FoodOrderDomain.OrderStates", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrderState")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.ToTable("OrderStates");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            AddedDate = new DateTime(2024, 4, 27, 19, 39, 46, 501, DateTimeKind.Local).AddTicks(4157),
                            ModifiedDate = new DateTime(2024, 4, 27, 19, 39, 46, 501, DateTimeKind.Local).AddTicks(4174),
                            OrderState = "Hazırlanıyor",
                            Status = true
                        },
                        new
                        {
                            ID = 2,
                            AddedDate = new DateTime(2024, 4, 27, 19, 39, 46, 501, DateTimeKind.Local).AddTicks(4176),
                            ModifiedDate = new DateTime(2024, 4, 27, 19, 39, 46, 501, DateTimeKind.Local).AddTicks(4176),
                            OrderState = "Teslim Edildi",
                            Status = true
                        },
                        new
                        {
                            ID = 3,
                            AddedDate = new DateTime(2024, 4, 27, 19, 39, 46, 501, DateTimeKind.Local).AddTicks(4178),
                            ModifiedDate = new DateTime(2024, 4, 27, 19, 39, 46, 501, DateTimeKind.Local).AddTicks(4179),
                            OrderState = "İptal Edildi",
                            Status = true
                        });
                });

            modelBuilder.Entity("FoodOrderDomain.Orders", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("AddressID")
                        .HasColumnType("int");

                    b.Property<int?>("ContactID")
                        .HasColumnType("int");

                    b.Property<int?>("CustomerID")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrderNotes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderStateID")
                        .HasColumnType("int");

                    b.Property<int>("PaymentMethodID")
                        .HasColumnType("int");

                    b.Property<bool>("PaymentStatus")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.HasIndex("AddressID");

                    b.HasIndex("ContactID");

                    b.HasIndex("CustomerID");

                    b.HasIndex("OrderStateID");

                    b.HasIndex("PaymentMethodID");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("FoodOrderDomain.PaymentMethods", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.ToTable("PaymentMethods");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            AddedDate = new DateTime(2024, 4, 27, 19, 39, 46, 501, DateTimeKind.Local).AddTicks(4466),
                            ModifiedDate = new DateTime(2024, 4, 27, 19, 39, 46, 501, DateTimeKind.Local).AddTicks(4467),
                            PaymentName = "Kredi/Banka Kartı",
                            Status = true
                        },
                        new
                        {
                            ID = 2,
                            AddedDate = new DateTime(2024, 4, 27, 19, 39, 46, 501, DateTimeKind.Local).AddTicks(4468),
                            ModifiedDate = new DateTime(2024, 4, 27, 19, 39, 46, 501, DateTimeKind.Local).AddTicks(4469),
                            PaymentName = "Nakit",
                            Status = true
                        });
                });

            modelBuilder.Entity("FoodOrderDomain.ProductDetails", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.HasIndex("ProductID")
                        .IsUnique();

                    b.ToTable("ProductDetails");
                });

            modelBuilder.Entity("FoodOrderDomain.ProductMenu", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("MenuID")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.HasIndex("MenuID");

                    b.HasIndex("ProductID");

                    b.ToTable("ProductMenu");
                });

            modelBuilder.Entity("FoodOrderDomain.Products", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PreparationTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductDetailID")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.HasIndex("CategoryID");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("FoodOrderDomain.Stock", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("MenuID")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<int>("StockAmount")
                        .HasColumnType("int");

                    b.Property<bool>("StockStatus")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.HasIndex("MenuID")
                        .IsUnique();

                    b.HasIndex("ProductID")
                        .IsUnique();

                    b.ToTable("Stocks");
                });

            modelBuilder.Entity("FoodOrderDomain.AddressInformations", b =>
                {
                    b.HasOne("FoodOrderDomain.Cities", "City")
                        .WithMany("AddressInfo")
                        .HasForeignKey("CityID");

                    b.HasOne("FoodOrderDomain.Countries", "Country")
                        .WithMany("AddressInfo")
                        .HasForeignKey("CountryID");

                    b.HasOne("FoodOrderDomain.Counties", "County")
                        .WithMany("AddressInfo")
                        .HasForeignKey("CountyID");

                    b.HasOne("FoodOrderDomain.Customers", "Customer")
                        .WithMany("AddressInfo")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("Country");

                    b.Navigation("County");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("FoodOrderDomain.Cities", b =>
                {
                    b.HasOne("FoodOrderDomain.Countries", "Country")
                        .WithMany("City")
                        .HasForeignKey("CountryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("FoodOrderDomain.ContactInformations", b =>
                {
                    b.HasOne("FoodOrderDomain.ContactTypes", "ContactType")
                        .WithMany("ContactInfo")
                        .HasForeignKey("ContactTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FoodOrderDomain.Customers", "Customer")
                        .WithMany("ContactInfo")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContactType");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("FoodOrderDomain.Counties", b =>
                {
                    b.HasOne("FoodOrderDomain.Cities", "City")
                        .WithMany("County")
                        .HasForeignKey("CityID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("FoodOrderDomain.OrderDetails", b =>
                {
                    b.HasOne("FoodOrderDomain.Menu", "Menu")
                        .WithMany()
                        .HasForeignKey("MenuID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FoodOrderDomain.Orders", "Order")
                        .WithMany()
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Menu");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("FoodOrderDomain.Orders", b =>
                {
                    b.HasOne("FoodOrderDomain.AddressInformations", "Address")
                        .WithMany("Orders")
                        .HasForeignKey("AddressID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FoodOrderDomain.ContactInformations", "ContactInfo")
                        .WithMany("Orders")
                        .HasForeignKey("ContactID");

                    b.HasOne("FoodOrderDomain.Customers", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerID");

                    b.HasOne("FoodOrderDomain.OrderStates", "OrderState")
                        .WithMany("Orders")
                        .HasForeignKey("OrderStateID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FoodOrderDomain.PaymentMethods", "PaymentMethod")
                        .WithMany("Orders")
                        .HasForeignKey("PaymentMethodID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("ContactInfo");

                    b.Navigation("Customer");

                    b.Navigation("OrderState");

                    b.Navigation("PaymentMethod");
                });

            modelBuilder.Entity("FoodOrderDomain.ProductDetails", b =>
                {
                    b.HasOne("FoodOrderDomain.Products", "Product")
                        .WithOne("ProductDetail")
                        .HasForeignKey("FoodOrderDomain.ProductDetails", "ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("FoodOrderDomain.ProductMenu", b =>
                {
                    b.HasOne("FoodOrderDomain.Menu", "Menu")
                        .WithMany()
                        .HasForeignKey("MenuID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FoodOrderDomain.Products", "Product")
                        .WithMany()
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Menu");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("FoodOrderDomain.Products", b =>
                {
                    b.HasOne("FoodOrderDomain.Categories", "Category")
                        .WithMany("Product")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("FoodOrderDomain.Stock", b =>
                {
                    b.HasOne("FoodOrderDomain.Menu", "Menu")
                        .WithOne("Stock")
                        .HasForeignKey("FoodOrderDomain.Stock", "MenuID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FoodOrderDomain.Products", "Product")
                        .WithOne("Stock")
                        .HasForeignKey("FoodOrderDomain.Stock", "ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Menu");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("FoodOrderDomain.AddressInformations", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("FoodOrderDomain.Categories", b =>
                {
                    b.Navigation("Product");
                });

            modelBuilder.Entity("FoodOrderDomain.Cities", b =>
                {
                    b.Navigation("AddressInfo");

                    b.Navigation("County");
                });

            modelBuilder.Entity("FoodOrderDomain.ContactInformations", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("FoodOrderDomain.ContactTypes", b =>
                {
                    b.Navigation("ContactInfo");
                });

            modelBuilder.Entity("FoodOrderDomain.Counties", b =>
                {
                    b.Navigation("AddressInfo");
                });

            modelBuilder.Entity("FoodOrderDomain.Countries", b =>
                {
                    b.Navigation("AddressInfo");

                    b.Navigation("City");
                });

            modelBuilder.Entity("FoodOrderDomain.Customers", b =>
                {
                    b.Navigation("AddressInfo");

                    b.Navigation("ContactInfo");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("FoodOrderDomain.Menu", b =>
                {
                    b.Navigation("Stock")
                        .IsRequired();
                });

            modelBuilder.Entity("FoodOrderDomain.OrderStates", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("FoodOrderDomain.PaymentMethods", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("FoodOrderDomain.Products", b =>
                {
                    b.Navigation("ProductDetail")
                        .IsRequired();

                    b.Navigation("Stock")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
